# .github/actions/android-build-test/action.yml
name: 'Android Build and Test'
description: Checks out the repo, Setup Java, Give permissions to gradle

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    - name: Change wrapper permissions
      run: chmod +x ./gradlew
      shell: bash